# NumPy

**NumPy**--which stands for Numerical Python--is the foundational package for performing scientific computing. In addition, it provides the primary data structure--*the n-dimensional array*--on which the **pandas** package is built. NumPy includes extensive functionality, but we will use it primarily for:

* Fast (vectorized) array operations for data processing
* Efficient descriptive statistics
* Manipulations for merging multiple data sets

Friendly reminders:

* NumPy module on DataCamp is due by 11:59 p.m. tonight
* Homework #1 is due by 11:59 p.m. tonight
* Homework #2 is released

In [1]:
# Import statement
import numpy as np

## ndarrays

The ndarray is an n-dimensional array object, similar to a list but designed to facilitate fast computation. However, in order for arrays to be useful, they must hold a single type of object. We will mostly focus on numerical (int, float) and boolean arrays.

Arrays will most likely be loaded from external data sources (later), but for now, we can create them via casting (using the np.**array** function) or using one of the following generating functions (or class of functions):

* np.**arange**(*start*, *stop*, *step*) (similar to range function for lists)
* np.**zeros**(*shape*), np.**ones**(*shape*) (where *shape* is a sequence of dimension sizes)
* np.random.**rand**(*d0*,*d1*,...,*dn*) (where *d0*,*d1*,...,*dn* are dimension sizes)
* np.random.**randn**(*d0*,*d1*,...,*dn*) (where *d0*,*d1*,...,*dn* are dimension sizes)

In [2]:
np.zeros(shape)

NameError: name 'shape' is not defined

In [3]:
# Casting from list
np.array([1,5,-1,2,4])

array([ 1,  5, -1,  2,  4])

In [4]:
# np.arange
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# np.ones, np.zeros ****(row,colmun)****
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [6]:
# np.random.rand, np.random(normalD).randn(0-1)
arr2d = np.random.rand(3,3)
arr2d

array([[0.0353899 , 0.48904223, 0.16637835],
       [0.74651292, 0.98656297, 0.40644948],
       [0.7868014 , 0.1496109 , 0.60034595]])

In [9]:
arr2d. #Tab to search
dir(arr2d)
?arr2d

SyntaxError: invalid syntax (<ipython-input-9-deee388560ef>, line 1)

In [7]:
# Common attributes
print(arr2d.ndim) # number of dimensions
print(arr2d.shape) # shape of array
print(arr2d.dtype) # data type

2
(3, 3)
float64


In [8]:
# Casting to other dtypes
np.arange(10).astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [9]:
# Tab completion
arr1d.

<function ndarray.all>

See https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html for additional details on ndarray objects.

## Array Operations

As previously stated, arrays are designed to support fast computation and comparison. The most common type of operations are:

* Between arrays and scalars
* Universal functions (np.func)
    - Unary (performed on a single array): abs, sqrt, exp, log, ceil, floor, logical_not, and more
    - Binary (performed between two arrays): +, -, /, *, **, min, max, mod, >, >=, <, <=, ==, !=, logical_and, logical_or, logical_xor
* Mathematical and statistical functions - Available as NumPy functions (np.func) and array methods (arr.func)
    - Aggregation: mean, sum, std, var, min/max, argmin/argmax
    - Non-aggregation: cumsum, cumprod

In [10]:
# Broadcasting with a scalar
arr2d + 1

array([[1.0353899 , 1.48904223, 1.16637835],
       [1.74651292, 1.98656297, 1.40644948],
       [1.7868014 , 1.1496109 , 1.60034595]])

In [11]:
# Broadcasting with 1-d array
arr2d + [1,2,3]

array([[1.0353899 , 2.48904223, 3.16637835],
       [1.74651292, 2.98656297, 3.40644948],
       [1.7868014 , 2.1496109 , 3.60034595]])

In [12]:
# Comparison with a scalar
arr2d > 0.5

array([[False, False, False],
       [ True,  True, False],
       [ True, False,  True]])

In [13]:
# Unary functions
np.sqrt(arr2d)

array([[0.18812202, 0.69931554, 0.40789502],
       [0.86400979, 0.99325876, 0.63753391],
       [0.88701826, 0.38679568, 0.77481994]])

In [14]:
# Binary functions
arr2d * arr2d

array([[0.00125244, 0.2391623 , 0.02768176],
       [0.55728154, 0.97330649, 0.16520118],
       [0.61905644, 0.02238342, 0.36041526]])

In [15]:
# Aggregation function
print(np.mean(arr2d,axis=0))#col
print(np.mean(arr2d,axis=1))#row

[0.52290141 0.5417387  0.39105793]
[0.23027016 0.71317512 0.51225275]


In [16]:
# Non-aggregation function
arr2d.cumsum()

array([0.0353899 , 0.52443212, 0.69081047, 1.4373234 , 2.42388636,
       2.83033585, 3.61713725, 3.76674815, 4.36709409])

## Arrays vs. Lists

Arrays may seem similar to lists (e.g., they are both mutable and iterable sequences), but they are distinct data structures. Be sure to use an array whenever you are performing any large scale computations or comparisons.

In [17]:
# List operations
L = list(range(10))
print(L + L)
print(L * 3)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [18]:
# Array operations
arr = np.arange(10)
print(arr + arr);
print(arr * 3);

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  3  6  9 12 15 18 21 24 27]


In [19]:
%%timeit -r5 -n10000
# List computation - for loop
squares = []
for x in L:
    squares.append(x)

995 ns ± 129 ns per loop (mean ± std. dev. of 5 runs, 10000 loops each)


In [20]:
# List computation - map
lf = lambda x: x * x
%timeit -r5 -n10000 map(lf, L)

198 ns ± 5.7 ns per loop (mean ± std. dev. of 5 runs, 10000 loops each)


In [21]:
# List computation - list comprehension
%timeit -r5 -n10000 [x * x  for x in L]

749 ns ± 36.3 ns per loop (mean ± std. dev. of 5 runs, 10000 loops each)


In [22]:
# List computation - generator expression
%timeit -r5 -n10000 (x * x  for x in L)

379 ns ± 53.4 ns per loop (mean ± std. dev. of 5 runs, 10000 loops each)


In [23]:
# Array computations
%timeit -r5 -n10000 arr ** 2
%timeit -r5 -n10000 np.square(arr)
%timeit -r5 -n10000 arr * arr

908 ns ± 109 ns per loop (mean ± std. dev. of 5 runs, 10000 loops each)
1.08 µs ± 253 ns per loop (mean ± std. dev. of 5 runs, 10000 loops each)
683 ns ± 102 ns per loop (mean ± std. dev. of 5 runs, 10000 loops each)


In addition, lists do not have restrictions on the size of nested sequences, whereas arrays have restrictions for constructing a useful form of the object.

In [24]:
[[1,2,3],[4,5,6,7],[8,9]]

[[1, 2, 3], [4, 5, 6, 7], [8, 9]]

In [25]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Indexing and Slicing

Indexing and slicing arrays is similar to lists...

In [26]:
print(arr[5])
print(arr[-1])
print(arr[5:8])
print(arr[::2])

5
9
[5 6 7]
[0 2 4 6 8]


...but unlike lists, array slices are views on the original array, so any updates to the array slice will be reflected in the original array. Consider the following example, in which we combine indexing with assignment (which also works as you would expect).

In [27]:
list_slice = L[5:8]
list_slice[0] = -10
print(list_slice, L)

[-10, 6, 7] [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [31]:
arr_slice = arr[5:8]
arr_slice[0] = -10
print(arr_slice, arr)

[-10   6   7] [  0   1   2   3   4 -10   6   7   8   9]


Indexing via index and boolean arrays are convenient ways of filtering an array. In this case, these operations return a copy of the array, as opposed to a view on the original array as in the case of slicing.

In [28]:
# Index arrays - Each element in the index array is replaced by the corresponding value in the array
arr[np.array([1,0,1,3,9,-1])]

array([1, 0, 1, 3, 9, 9])

In [29]:
# Boolean arrays - Each element in the array is returned if the corresponding boolean scalar is True
arr[np.array([True, False, False, False, False, True, False, False, False, False])]

array([0, 5])

In [30]:
# Filtering via conditional
arr[arr % 5 == 0]

array([0, 5])

You can also use boolean arrays to learn about your data.

In [31]:
# How much of my data satisfies a given condition?
arr = np.random.randn(100)
(arr > 0).sum() #T 1 F 0

54

In [32]:
# Do any of my data satisfy a given condition?
(arr > 3).any() #out of 3SD

True

In [33]:
# Do all of my data satisfy a given condition?
(np.abs(arr) < 3).all()

False

Indexing and slicing multi-dimensional arrays is fairly intuitive. Whereas a single dimensional array contains 0-dimensional values (scalars), a 2-dimensional array is an array of 1-d arrays, where the first dimension represents the position of each 1-d array, and the second dimension refers to a specific position within each 1-d array (where all 1-d arrays have the same length). Similarly, a 3-dimension array has 3 dimensions corresponding to the position of each 2-d array, 1-d array, and scalar value, respectively. And so on, for higher dimensions.

![](https://i.stack.imgur.com/R2IDC.png "Multi-dimensional arrays")

When indexing and slicing into an n-d array, each dimension is accessed in order, either via successive indexing or slicing operations or a sequence of dimensional indices or slices. To retain all of the elements for a particular dimension, use the ':' operator.

In [34]:
# 2-d array
arr2d = np.random.rand(3,3)
arr2d

array([[0.7445287 , 0.91004461, 0.88973248],
       [0.83345694, 0.7828525 , 0.06259683],
       [0.42542708, 0.00217241, 0.00131896]])

In [35]:
# Index specific element
print(arr2d[0][0])
print(arr2d[0,0])

0.7445287041795936
0.7445287041795936


In [36]:
# Slice rows
print(arr2d[0])
print(arr2d[0,:])

[0.7445287  0.91004461 0.88973248]
[0.7445287  0.91004461 0.88973248]


In [37]:
# Slice columns
arr2d[:,0]

array([0.7445287 , 0.83345694, 0.42542708])

In [38]:
# Fancy slicing
arr2d[1:,:2]

array([[0.83345694, 0.7828525 ],
       [0.42542708, 0.00217241]])

In [39]:
# 3-d array
arr3d = np.random.rand(3,3,3).astype(float)
arr3d

array([[[0.79760216, 0.97607183, 0.987604  ],
        [0.95840659, 0.40380481, 0.86174602],
        [0.3491364 , 0.95386019, 0.73008263]],

       [[0.1022267 , 0.98008574, 0.26817813],
        [0.71913232, 0.96496614, 0.28394374],
        [0.51826844, 0.3708075 , 0.03253725]],

       [[0.92544024, 0.78300607, 0.15566763],
        [0.77804286, 0.29323666, 0.41158636],
        [0.37001263, 0.86982771, 0.16651317]]])

In [40]:
# Index specific 2-d array
print(arr3d[1])
print(arr3d[1,:,:])

[[0.1022267  0.98008574 0.26817813]
 [0.71913232 0.96496614 0.28394374]
 [0.51826844 0.3708075  0.03253725]]
[[0.1022267  0.98008574 0.26817813]
 [0.71913232 0.96496614 0.28394374]
 [0.51826844 0.3708075  0.03253725]]


In [41]:
# Slicing 3-d array
arr3d[:,1,:]

array([[0.95840659, 0.40380481, 0.86174602],
       [0.71913232, 0.96496614, 0.28394374],
       [0.77804286, 0.29323666, 0.41158636]])

## Other Important Array Methods

### Conditional Logic

We saw that ternary expressions were a convenient way for us to generate conditional values:

*expr1* if *cond* else *expr2*

There are several ways to perform this task for a list (which we could then cast to an array):

1. Use a **for** loop
2. Use **map** with a lambda function
3. Use a list comprehension

For arrays, we use the np.**where** function!

In [42]:
np.where?

In [43]:
# Flip a coin N times
N = 10
np.where(np.random.rand(N) > 0.5, 'H', 'T')

array(['T', 'T', 'T', 'T', 'H', 'H', 'H', 'H', 'T', 'H'], dtype='<U1')

In [44]:
# Select a value at random
N = 10
a = np.arange(N)
b = np.zeros(N)
np.where(np.random.rand(N) > 0.5, a, b)

array([0., 0., 0., 0., 0., 0., 6., 0., 0., 9.])

In [45]:
# Nested conditions
N = 10
a = np.ones(N)
b = np.zeros(N)
c = -np.ones(N)
np.where(np.random.rand(N) > 2/3, a, np.where(np.random.rand(N) > 1/2, b, c))

array([ 0., -1.,  0., -1.,  0.,  0.,  1., -1.,  0., -1.])

### Sorting

In [46]:
arr = np.random.rand(10)
arr

array([0.59320004, 0.9342632 , 0.1897503 , 0.50519529, 0.33665049,
       0.80187432, 0.67890231, 0.32672303, 0.917295  , 0.8736065 ])

In [47]:
# Return a copy of sorted array
np.sort(arr)

array([0.1897503 , 0.32672303, 0.33665049, 0.50519529, 0.59320004,
       0.67890231, 0.80187432, 0.8736065 , 0.917295  , 0.9342632 ])

In [48]:
# Return sorting indices
arr.argsort()

array([2, 7, 4, 3, 0, 6, 5, 9, 8, 1])

In [49]:
# Sort in place
arr.sort()
arr

array([0.1897503 , 0.32672303, 0.33665049, 0.50519529, 0.59320004,
       0.67890231, 0.80187432, 0.8736065 , 0.917295  , 0.9342632 ])

In [50]:
# Search sorted
u = np.random.rand()
print(u, arr.searchsorted(u))

0.7389429243416294 6


### Set Logic

In [51]:
arr1 = np.arange(10)
arr2 = np.arange(20,0,-2)
print(arr1, arr2)

[0 1 2 3 4 5 6 7 8 9] [20 18 16 14 12 10  8  6  4  2]


In [52]:
# Membership
7 in arr2

False

In [53]:
# Unique elements
print(arr1 * arr2, np.unique(arr1 * arr2))

[ 0 18 32 42 48 50 48 42 32 18] [ 0 18 32 42 48 50]


In [54]:
# Comparisons - np.intersect1d, .union1d, setdiff1d, setxor1d
np.setxor1d(arr1, arr2)

array([ 0,  1,  3,  5,  7,  9, 10, 12, 14, 16, 18, 20])

## Manipulating and Combining Arrays

Sometimes, you will need to manipulate or combine multiple arrays of data prior to performing any analysis. There are a lot of built-in functions for these purposes. Very rarely will you need to develop your own code.

#### Manipulating Arrays

In [61]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [62]:
# Reshaping arrays
print(arr.reshape((2,4)))
print(arr.reshape((2,-1))) # automatically determines the other dimension size

[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]


In [68]:
# Transpose
print(arr)
arr.reshape((2,4)).T # Our first example of chaining methods together

[0 1 2 3 4 5 6 7]


array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [69]:
# Flatten
print(arr.reshape((2,4)).flatten('C')) # row-major
print(arr.reshape((2,4)).flatten('F')) # column-major

[0 1 2 3 4 5 6 7]
[0 4 1 5 2 6 3 7]


#### Combining and Splitting Arrays

In [70]:
arr1 = np.random.rand(4,2)
arr2 = np.random.rand(4,2)
print(arr1)
print(arr2)

[[0.39804676 0.09499713]
 [0.37421124 0.85041543]
 [0.53494414 0.36796021]
 [0.51560415 0.71448169]]
[[0.77183639 0.46733144]
 [0.79038246 0.05591297]
 [0.67010196 0.88272699]
 [0.1067269  0.24695059]]


In [71]:
# Concatenation by row
np.concatenate([arr1, arr2], axis=0)

array([[0.39804676, 0.09499713],
       [0.37421124, 0.85041543],
       [0.53494414, 0.36796021],
       [0.51560415, 0.71448169],
       [0.77183639, 0.46733144],
       [0.79038246, 0.05591297],
       [0.67010196, 0.88272699],
       [0.1067269 , 0.24695059]])

In [72]:
# Stacking rows
np.vstack([arr1, arr2]) # also, np.row_stack

array([[0.39804676, 0.09499713],
       [0.37421124, 0.85041543],
       [0.53494414, 0.36796021],
       [0.51560415, 0.71448169],
       [0.77183639, 0.46733144],
       [0.79038246, 0.05591297],
       [0.67010196, 0.88272699],
       [0.1067269 , 0.24695059]])

In [73]:
# Concatenate by column
np.concatenate([arr1, arr2], axis=1)

array([[0.39804676, 0.09499713, 0.77183639, 0.46733144],
       [0.37421124, 0.85041543, 0.79038246, 0.05591297],
       [0.53494414, 0.36796021, 0.67010196, 0.88272699],
       [0.51560415, 0.71448169, 0.1067269 , 0.24695059]])

In [74]:
# Stacking columns
np.hstack([arr1, arr2]) # also, np.column_stack

array([[0.39804676, 0.09499713, 0.77183639, 0.46733144],
       [0.37421124, 0.85041543, 0.79038246, 0.05591297],
       [0.53494414, 0.36796021, 0.67010196, 0.88272699],
       [0.51560415, 0.71448169, 0.1067269 , 0.24695059]])

In [75]:
# Splitting arrays
np.split(arr1, [1,2], axis=0) # also, np.hsplit, vsplit

[array([[0.39804676, 0.09499713]]),
 array([[0.37421124, 0.85041543]]),
 array([[0.53494414, 0.36796021],
        [0.51560415, 0.71448169]])]

## File Input/Output

There are two primary ways to save/load NumPy arrays to/from a file:

* Binary format (.npy) - np.**save** and np.**load**
* Delimited text file (.txt) - np.**savetxt** and np.**loadtxt** (also, np.**genfromtext** for files with missing data)

In [76]:
# Print working directory
%pwd

'/Users/weiyaoma/Desktop/X jupyter notebook'

In [ ]:
# Change working directory to data folder
%cd ~/Dropbox/Teaching/Courses/BUDT758X/data/

In [ ]:
# Save arr2d to binary file
np.save('arr2d', arr2d) # function will add the .npy extension

In [ ]:
# Delete arr2d and re-load from file
del arr2d
arr2d = np.load('arr2d.npy') # must include .npy extension
arr2d

In [ ]:
# Save arr2d to text file
np.savetxt('arr2d.txt', arr2d, fmt='%.4f', delimiter=',')

In [ ]:
# Delete arr2d and re-load from file
del arr2d
arr2d = np.loadtxt('arr2d.txt', delimiter=',')
arr2d

## Next Time: NumPy Lab